name: firestore_ui
description: A port of firebase_database's FirebaseAnimatedList
version: 1.11.0
homepage: https://github.com/gildaswise/firestore_ui
# author: Gildásio Filho <gildasiogx@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6 
  firebase_core: ^0.7.0
  firebase_core_platform_interface: ^3.0.1
  cloud_firestore: ^0.16.0+1
  cloud_firestore_platform_interface: ^3.0.0
  flutter_staggered_grid_view: ^0.3.0
  collection: ^1.14.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
